name: ci

on:
  push:
    branches:
      - master
      - dev
    tags:
      - '*'     
  pull_request:
    branches:
      - master
      - dev
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - unlocked
      - review_requested
  workflow_dispatch:
    
env:
  DOCKER_REGISTRY_REPOSITORY: sysflowtelemetry/sf-collector  

jobs:     
  tests:    
    runs-on: ubuntu-latest  
    steps:      
      - name: Checkout
        uses: actions/checkout@v2  
        with:
          submodules: recursive 
          fetch-depth: 0     
      - name: Init modules
        run: make -C modules init        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1            
      - name: Run tests
        run: |
          DOCKER_BUILDKIT=1 docker build --target testing -t sf-collector:testing .
          docker run --rm --name sftests -v "$(pwd)/tests:/usr/local/sysflow/tests" -e quiet=true sf-collector:testing -t tests/tests.bats            
  docker:    
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: read
      packages: write
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive 
          fetch-depth: 0         
      - name: Init modules
        run: make -C modules init
      - name: Build container
        id: meta
        uses: docker/metadata-action@v3
        with:          
          images: |
            ${{ env.DOCKER_REGISTRY_REPOSITORY }}
            ghcr.io/${{ github.repository }}
          tags: |            
            type=edge,branch=master
            type=match,pattern=dev
            type=ref,event=tag            
            type=ref,event=pr         
            type=semver,pattern={{version}}
          labels: |
            org.opencontainers.image.documentation=https://sysflow.readthedocs.io/
            org.opencontainers.image.vendor=SysFlow
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}  
      - name: Set build args
        id: args
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"  
      - name: Build and push
        id: docker_build        
        uses: docker/build-push-action@v2        
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"          
          target: runtime
          build-args: |
            BUILD_NUMBER=${{ steps.args.outputs.sha_short }}
            VERSION=${{ steps.args.outputs.branch }}
            RELEASE=${{ steps.args.outputs.sha_short }}
      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        if: ${{ github.ref == 'refs/heads/master' && github.event_name != 'pull_request' }}
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_TOKEN }}
        with:
          destination_container_repo: ${{ env.DOCKER_REGISTRY_REPOSITORY }}
          provider: dockerhub          
          readme_file: "README.md"           
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
